export const enum ZrInstructionType {
    GetStack,
    SetStack,
    GetConstant,
    SetConstant,
    GetClosure,
    SetClosure,
    AddInt,
    AddFloat,
    AddString,
    SubInt,
    SubFloat,
    MulSigned,
    MulUnsigned,
    MulFloat,
    DivSigned,
    DivUnsigned,
    DivFloat,
    ModSigned,
    ModUnsigned,
    ModFloat,
    PowSigned,
    PowUnsigned,
    PowFloat,
    ShiftLeft,
    ShiftRight,
    LogicalNot,
    LogicalAnd,
    LogicalOr,
    LogicalGreaterSigned,
    LogicalGreaterUnsigned,
    LogicalGreaterFloat,
    LogicalLessSigned,
    LogicalLessUnsigned,
    LogicalLessFloat,
    LogicalEqual,
    LogicalNotEqual,
    LogicalGreaterEqualSigned,
    LogicalGreaterEqualUnsigned,
    LogicalGreaterEqualFloat,
    LogicalLessEqualSigned,
    LogicalLessEqualUnsigned,
    LogicalLessEqualFloat,
    BitwiseNot,
    BitwiseAnd,
    BitwiseOr,
    BitwiseXor,
    BitwiseShiftLeft,
    BitwiseShiftRight,
    FunctionCall,
    FunctionTailCall,
    FunctionReturn,
    GetValue,
    SetValue,
    Jump,
    JumpIf,
    CreateClosure,
    Try,
    Throw,
    Catch
}

export const ZrInstructionTypeMap = {
    [ZrInstructionType.GetStack]: "GetStack",
    [ZrInstructionType.SetStack]: "SetStack",
    [ZrInstructionType.GetConstant]: "GetConstant",
    [ZrInstructionType.SetConstant]: "SetConstant",
    [ZrInstructionType.GetClosure]: "GetClosure",
    [ZrInstructionType.SetClosure]: "SetClosure",
    [ZrInstructionType.AddInt]: "AddInt",
    [ZrInstructionType.AddFloat]: "AddFloat",
    [ZrInstructionType.AddString]: "AddString",
    [ZrInstructionType.SubInt]: "SubInt",
    [ZrInstructionType.SubFloat]: "SubFloat",
    [ZrInstructionType.MulSigned]: "MulSigned",
    [ZrInstructionType.MulUnsigned]: "MulUnsigned",
    [ZrInstructionType.MulFloat]: "MulFloat",
    [ZrInstructionType.DivSigned]: "DivSigned",
    [ZrInstructionType.DivUnsigned]: "DivUnsigned",
    [ZrInstructionType.DivFloat]: "DivFloat",
    [ZrInstructionType.ModSigned]: "ModSigned",
    [ZrInstructionType.ModUnsigned]: "ModUnsigned",
    [ZrInstructionType.ModFloat]: "ModFloat",
    [ZrInstructionType.PowSigned]: "PowSigned",
    [ZrInstructionType.PowUnsigned]: "PowUnsigned",
    [ZrInstructionType.PowFloat]: "PowFloat",
    [ZrInstructionType.ShiftLeft]: "ShiftLeft",
    [ZrInstructionType.ShiftRight]: "ShiftRight",
    [ZrInstructionType.LogicalNot]: "LogicalNot",
    [ZrInstructionType.LogicalAnd]: "LogicalAnd",
    [ZrInstructionType.LogicalOr]: "LogicalOr",
    [ZrInstructionType.LogicalGreaterSigned]: "LogicalGreaterSigned",
    [ZrInstructionType.LogicalGreaterUnsigned]: "LogicalGreaterUnsigned",
    [ZrInstructionType.LogicalGreaterFloat]: "LogicalGreaterFloat",
    [ZrInstructionType.LogicalLessSigned]: "LogicalLessSigned",
    [ZrInstructionType.LogicalLessUnsigned]: "LogicalLessUnsigned",
    [ZrInstructionType.LogicalLessFloat]: "LogicalLessFloat",
    [ZrInstructionType.LogicalEqual]: "LogicalEqual",
    [ZrInstructionType.LogicalNotEqual]: "LogicalNotEqual",
    [ZrInstructionType.LogicalGreaterEqualSigned]: "LogicalGreaterEqualSigned",
    [ZrInstructionType.LogicalGreaterEqualUnsigned]: "LogicalGreaterEqualUnsigned",
    [ZrInstructionType.LogicalGreaterEqualFloat]: "LogicalGreaterEqualFloat",
    [ZrInstructionType.LogicalLessEqualSigned]: "LogicalLessEqualSigned",
    [ZrInstructionType.LogicalLessEqualUnsigned]: "LogicalLessEqualUnsigned",
    [ZrInstructionType.LogicalLessEqualFloat]: "LogicalLessEqualFloat",
    [ZrInstructionType.BitwiseNot]: "BitwiseNot",
    [ZrInstructionType.BitwiseAnd]: "BitwiseAnd",
    [ZrInstructionType.BitwiseOr]: "BitwiseOr",
    [ZrInstructionType.BitwiseXor]: "BitwiseXor",
    [ZrInstructionType.BitwiseShiftLeft]: "BitwiseShiftLeft",
    [ZrInstructionType.BitwiseShiftRight]: "BitwiseShiftRight",
    [ZrInstructionType.FunctionCall]: "FunctionCall",
    [ZrInstructionType.FunctionTailCall]: "FunctionTailCall",
    [ZrInstructionType.FunctionReturn]: "FunctionReturn",
    [ZrInstructionType.GetValue]: "GetValue",
    [ZrInstructionType.SetValue]: "SetValue",
    [ZrInstructionType.Jump]: "Jump",
    [ZrInstructionType.JumpIf]: "JumpIf",
    [ZrInstructionType.CreateClosure]: "CreateClosure",
    [ZrInstructionType.Try]: "Try",
    [ZrInstructionType.Throw]: "Throw",
    [ZrInstructionType.Catch]: "Catch"
};

export const ZrInstructionTypeNameMap: Map<string, ZrInstructionType> = new Map();
for (const [key, value] of Object.entries(ZrInstructionTypeMap)) {
    ZrInstructionTypeNameMap.set(value, key as any as ZrInstructionType);
}
