import "./types";
import "./common/index";
import "./literals/index";
import "./types/index";
import "./statements/index";
import "./declarations/index";
import "./expressions/index";
import "./scriptHandler";
import "./moduleDeclarationHandler";
