import "./scope";
import "./blockScope";
import "./functionScope";
import "./propertyScope";
import "./enumScope";
import "./classScope";
import "./interfaceScope";
import "./structScope";
import "./moduleScope";
